INSERT INTO countries VALUES ('DE', 'Germany')
INSERT INTO countries VALUES ('UK', 'United Kingdom')
INSERT INTO countries VALUES ('US', 'United States of America')
GO

INSERT INTO states VALUES ('DE', '', '')
INSERT INTO states VALUES ('UK', 'ENG', 'England')
INSERT INTO states VALUES ('UK', 'NIR', 'Northern Ireland')
INSERT INTO states VALUES ('UK', 'SCT', 'Scotland')
INSERT INTO states VALUES ('UK', 'WLS', 'Wales')
INSERT INTO states VALUES ('US', 'AL', 'Alabama')
INSERT INTO states VALUES ('US', 'AK', 'Alaska')
INSERT INTO states VALUES ('US', 'AZ', 'Arizona')
INSERT INTO states VALUES ('US', 'AR', 'Arkansas')
INSERT INTO states VALUES ('US', 'CA', 'California')
INSERT INTO states VALUES ('US', 'CO', 'Colorado')
INSERT INTO states VALUES ('US', 'CT', 'Connecticut')
INSERT INTO states VALUES ('US', 'DE', 'Delaware')
INSERT INTO states VALUES ('US', 'DC', 'District of Columbia')
INSERT INTO states VALUES ('US', 'FL', 'Florida')
INSERT INTO states VALUES ('US', 'GA', 'Georgia')
INSERT INTO states VALUES ('US', 'HI', 'Hawaii')
INSERT INTO states VALUES ('US', 'ID', 'Idaho')
INSERT INTO states VALUES ('US', 'IL', 'Illinois')
INSERT INTO states VALUES ('US', 'IN', 'Indiana')
INSERT INTO states VALUES ('US', 'IA', 'Iowa')
INSERT INTO states VALUES ('US', 'KS', 'Kansas')
INSERT INTO states VALUES ('US', 'KY', 'Kentucky')
INSERT INTO states VALUES ('US', 'LA', 'Louisiana')
INSERT INTO states VALUES ('US', 'ME', 'Maine')
INSERT INTO states VALUES ('US', 'MD', 'Maryland')
INSERT INTO states VALUES ('US', 'MA', 'Massachusetts')
INSERT INTO states VALUES ('US', 'MI', 'Michigan')
INSERT INTO states VALUES ('US', 'MN', 'Minnesota')
INSERT INTO states VALUES ('US', 'MS', 'Mississippi')
INSERT INTO states VALUES ('US', 'MO', 'Missouri')
INSERT INTO states VALUES ('US', 'MT', 'Montana')
INSERT INTO states VALUES ('US', 'NE', 'Nebraska')
INSERT INTO states VALUES ('US', 'NV', 'Nevada')
INSERT INTO states VALUES ('US', 'NH', 'New Hampshire')
INSERT INTO states VALUES ('US', 'NJ', 'New Jersey')
INSERT INTO states VALUES ('US', 'NM', 'New Mexico')
INSERT INTO states VALUES ('US', 'NY', 'New York')
INSERT INTO states VALUES ('US', 'NC', 'North Carolina')
INSERT INTO states VALUES ('US', 'ND', 'North Dakota')
INSERT INTO states VALUES ('US', 'OH', 'Ohio')
INSERT INTO states VALUES ('US', 'OK', 'Oklahoma')
INSERT INTO states VALUES ('US', 'OR', 'Oregon')
INSERT INTO states VALUES ('US', 'PA', 'Pennsylvania')
INSERT INTO states VALUES ('US', 'RI', 'Rhode Island')
INSERT INTO states VALUES ('US', 'SC', 'South Carolina')
INSERT INTO states VALUES ('US', 'SD', 'South Dakota')
INSERT INTO states VALUES ('US', 'TN', 'Tennessee')
INSERT INTO states VALUES ('US', 'TX', 'Texas')
INSERT INTO states VALUES ('US', 'UT', 'Utah')
INSERT INTO states VALUES ('US', 'VT', 'Vermont')
INSERT INTO states VALUES ('US', 'VA', 'Virginia')
INSERT INTO states VALUES ('US', 'WA', 'Washington')
INSERT INTO states VALUES ('US', 'WV', 'West Virginia')
INSERT INTO states VALUES ('US', 'WI', 'Wisconsin')
INSERT INTO states VALUES ('US', 'WY', 'Wyoming')
GO

INSERT INTO customers VALUES ('Mr', 'David Norton', '49 Featherstone Street', NULL, 'Glasgow', 'G9 1DS', 'SCT', 'UK', NULL, 07700900113)
INSERT INTO customers VALUES ('Dr', 'Simon Galbraith', 'Red Gate Software Ltd', 'Cambridge Business Park', 'Cambridge', 'CB4 0WZ', 'ENG', 'UK', 'TRUE', 07700900127)
INSERT INTO customers VALUES ('Dr', 'Robert Hume', '5 Tall Cedar Road', NULL, 'Goose Island', '97014', 'OR', 'US', 'FALSE', 07700900131)
INSERT INTO customers VALUES ('Master', 'Joshua Falken', '1 Norad Road', NULL, 'Colorado Springs', '80914', 'CO', 'US', 'FALSE', 07700900149)
INSERT INTO customers VALUES ('Mrs', 'Birgit Meyer', 'Jungfernstieg 3', NULL, 'Hamburg', '20354', '', 'DE', 'TRUE', 07700900157)
GO
